image: docker:latest

services:
  - docker:dind

stages:
  - pre_build
  - build

variables:
  CI_REGISTRY_IMAGE: altmer/igroteka
  GIT_SUBMODULE_STRATEGY: recursive

build_assets:
  image: node:15.8.0-alpine3.13
  stage: pre_build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/

build:
  stage: build
  dependencies:
    - build_assets
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
